// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgoTpAixs6m_x_rwIhYC0yicBwBmeh9RE',
    appId: '1:958380258581:web:92d8d6cb01f7bd9b03a51c',
    messagingSenderId: '958380258581',
    projectId: 'authtutorial-aceac',
    authDomain: 'authtutorial-aceac.firebaseapp.com',
    storageBucket: 'authtutorial-aceac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqOJQNAtjB1jV2X43nZYsbrNuxQGsU2_A',
    appId: '1:958380258581:android:e9a887df55ebca5b03a51c',
    messagingSenderId: '958380258581',
    projectId: 'authtutorial-aceac',
    storageBucket: 'authtutorial-aceac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpFOsuPYKAwAjtiOPJoUm-OiL4ZLsITh0',
    appId: '1:958380258581:ios:b06b7a6d4d71918403a51c',
    messagingSenderId: '958380258581',
    projectId: 'authtutorial-aceac',
    storageBucket: 'authtutorial-aceac.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpFOsuPYKAwAjtiOPJoUm-OiL4ZLsITh0',
    appId: '1:958380258581:ios:b06b7a6d4d71918403a51c',
    messagingSenderId: '958380258581',
    projectId: 'authtutorial-aceac',
    storageBucket: 'authtutorial-aceac.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgoTpAixs6m_x_rwIhYC0yicBwBmeh9RE',
    appId: '1:958380258581:web:7c31b45b60c1fe3203a51c',
    messagingSenderId: '958380258581',
    projectId: 'authtutorial-aceac',
    authDomain: 'authtutorial-aceac.firebaseapp.com',
    storageBucket: 'authtutorial-aceac.firebasestorage.app',
  );
}
